version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-intl
    versions:
    - 5.10.19
    - 5.11.0
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
    - 5.13.0
    - 5.13.1
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.14.0
    - 5.15.3
    - 5.15.5
    - 5.15.7
    - 5.15.8
    - 5.16.0
    - 5.17.0
    - 5.17.1
  - dependency-name: "@formatjs/intl-pluralrules"
    versions:
    - 4.0.10
    - 4.0.11
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.15
    - 4.0.6
    - 4.0.8
    - 4.0.9
  - dependency-name: intl-messageformat-parser
    versions:
    - 6.3.1
    - 6.3.2
    - 6.3.4
    - 6.4.0
    - 6.4.1
    - 6.4.2
    - 6.4.3
  - dependency-name: "@formatjs/intl-relativetimeformat"
    versions:
    - 8.0.4
    - 8.0.6
    - 8.1.0
    - 8.1.1
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
