version: 2
jobs:
  build:
    working_directory: ~/website
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package.json" }}
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: eslint
          command: yarn run eslint
      - run:
          name: stylelint
          command: yarn run stylelint
      - run:
          name: build
          command: yarn build
  deploy:
    docker:
      - image: circleci/python:3-node
    working_directory: ~/website
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: yarn run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/circle-ci-config
