const FRAME = Object.freeze({
  FLORAL_TOP_LEFT: 'FLORAL_TOP_LEFT',
  FLORAL_BOTTOM_RIGHT: 'FLORAL_BOTTOM_RIGHT',
  LINED_TOP_LEFT: 'LINED_TOP_LEFT',
  LINED_BOTTOM_RIGHT: 'LINED_BOTTOM_RIGHT',
});

export { FRAME };
