const icon_enUS = {
  vnator: 'VNATOR',
  submiting: 'Submiting',
  chanel: {
    email: 'E-mail',
    linkedin: 'Linkedin',
    github: 'Github',
    medium: 'Medium',
    stackshare: 'Stackshare',
  },
  dev: {
    git: 'git',
    circleCi: 'CircliCi',
    jwt: 'JWT',
    vim: 'Vim',
    aws: 'AWS Amazon Web Service',
    arch: 'Arch Linux',
    firefox: 'Mozilla Firefox',
    duckduckgo: 'Duck Duck Go Search Engine',
    vscode: 'VSCode',
    shopify: 'Shopify',
  },
  archtectural: {
    kafka: 'Kafka',
    graphQl: 'GraphQL',
    awsLambda: 'AWS Lambda',
    awsEc2: 'AWS EC2',
    docker: 'Docker',
    kubernetes: 'Kubernetes',
    awsS3: 'AWS S3',
    awsCloudformation: 'AWS Cloudformation',
    awsApiGateway: 'AWS API Gateway',
    awsAmplify: 'AWS Amplify',
    awsCloudfront: 'AWS Cloudfront',
    awsCognito: 'AWS Cognito',
    awsRoute53: 'AWS Route53',
    serverless: 'Serverless',
  },
  languages: {
    rust: 'Rust',
    nodeJs: 'nodeJS',
    java: 'Java',
    python: 'Python',
    haskell: 'Haskell',
    tcl: 'TCL',
    cpp: 'C/C++',
  },
  persistence: {
    postgres: 'PostgreSQL',
    mySql: 'MySQL',
    sqlServer: 'SQLServer',
    awsAurora: 'AuroraDB',
    mongoDB: 'MongoDB',
    awsDynamoDB: 'DynamoDB',
    redis: 'Redis',
    django: 'Django',
    hibernate: 'Hibernate',
    sequelize: 'Sequelize',
  },
  frontend: {
    es2015: 'ES2015++',
    html: 'html5',
    css: 'css3',
    postcss: 'postCSS',
    cssModules: 'CSS Modules',
    typescript: 'Typescript',
    elm: 'Elm',
    wasm: 'Web Assembly (WASM)',
    react: 'ReactJs',
    redux: 'Redux',
    webpack: 'Webpack',
    yarn: 'Yarn',
    apollo: 'Apollo Client',
    eslint: 'ESLint',
    pwa: 'Progressive Web Application (PWA)',
  },
  mobile: {
    dart: 'Dart',
    flutter: 'Flutter',
    android: 'Android SDK',
    kotlin: 'Kotlin',
  },
};

export { icon_enUS };
