const icon_enUS = {
  archtectural: {
    kafka: 'Kafka',
    graphQL: 'GraphQL',
    awsLambda: 'AWS Lambda',
    awsEc2: 'AWS EC2',
    docker: 'Docker',
    awsS3: 'AWS S3', 
    awsCloudformation: 'AWS Cloudformation', 
    awsCognito: 'AWS Cognito',
    awsApiGateway: 'AWS API Gateway',
    serverless: 'Serverless',
  },
  languages: {
    rust: 'Rust',
    javascript: 'Javascript',
    java: 'Java',
    python: 'Python',
    haskell: 'Haskell',
    tcl: 'TCL',
  },
  persistence: {
    postgres: 'PostgreSQL',
    mySql: 'MySQL',
    sQLServer: 'sQLServer',
    aurora: 'AuroraDB',
    mongoDB: 'MongoDB',
    dynamoDB: 'DynamoDB',
    redis: 'Redis',
    django: 'Django',
    hibernate: 'Hibernate',
    sequelize: 'Sequelize',
  },
  frontend: {
    es2015: 'ES2015++',
    html5: 'html5',
    css3: 'css3',
    postcss: 'postCSS',
    cssModules: 'CSS Modules',
    typescript: 'Typescript',
    elm: 'Elm',
    wasm: 'Web Assembly (WASM)',
    react: 'ReactJs',
    apollo: 'Apollo Client',
    pws: 'Progressive Web Application (PWA)',
  },
  mobile: {
    reactNative: 'React Native',
    dart: 'Dart',
    flutter: 'Flutter',
    androidSDK: 'Android SDK',
    kotlin: 'Kotlin',
  },
};

export { tech_ptBR };
